### ISSUE TITLE
测试过程中发现只输出了一个标签，需要可视化一下预测结果，解决该问题

### ISSUE THREAD

**Issue by apollo600** [apollo600/WaterSegmentation#1]
案例1，蓝色标签没有被输出
![](https://cdn.jsdelivr.net/gh/apollo600/images@main/mac-mini/image-20230427231550216.png)

案例2，标签似乎给反了，不知道是标签的问题还是模型确实预测出错
![](https://cdn.jsdelivr.net/gh/apollo600/images@main/mac-mini/image-20230427231609863.png)
 
案例3，绿色标签没有被输出
![](https://cdn.jsdelivr.net/gh/apollo600/images@main/mac-mini/image-20230427231645639.png)

案例4，预测比较好的一张
![](https://cdn.jsdelivr.net/gh/apollo600/images@main/mac-mini/image-20230427231719578.png)

**Comment by apollo600** [comment]
经过可视化和对代码的检查，发现问题实际是其他类别的物体比较少，所以模型倾向于不学习其他类别，只学习了背景和水体

**Comment by apollo600** [comment]
可以参考这篇文章：https://paperswithcode.com/paper/optimized-u-net-for-brain-tumor-segmentation

**Optimized U-Net for Brain Tumor Segmentation**

We propose an optimized U-Net architecture for a brain tumor segmentation task in the BraTS21 challenge. **To find the optimal model architecture and the learning schedule, we have run an extensive ablation study to test**: deep supervision loss, Focal loss, decoder attention, drop block, and residual connections. Additionally, we have searched for the optimal depth of the U-Net encoder, number of convolutional channels and post-processing strategy. Our method won the validation phase and took third place in the test phase. We have open-sourced the code to reproduce our BraTS21 submission at the NVIDIA Deep Learning Examples GitHub Repository.

**Comment by Tastror** [comment]
改了一下颜色

顺便，现在正常 train 时提供 --log_visual 参数，会在每次 epoch 结束后输出 val_dataset 中前三个的图片至 log_root/log_dir 文件夹

**Comment by Tastror** [comment]
准备添加新的 model 了

问题后续参见 apollo600/WaterSegmentation#3

**Comment by Tastror** [comment]
在每次训练完前几个 epoch 后可以看看那个 log/train，有时候输出全黑，有时候全蓝（颜色我改过了，蓝水、橙垃圾、黑背景、绿叶子、白海藻）。说明初始参数的随机性没啥问题（）
